API: Add send_email method for sending custom emails
pretix/pretix pull request #3362
Opened 2023-05-27 10:20 UTC by chschenk

This PR adds the API function `send_email` which allows sending custom mails to buyers of tickets.

2023-06-02 18:04 UTC, raphaelm requested changes
Hey, thank you a lot! We'll need to see how we can prevent this from being abused for spamming on pretix.eu, but that's a concern for lager. I added a few notes for improvement.

2023-06-02 18:04 UTC, raphaelm commented on src/pretix/api/views/order.py
> +                            status=status.HTTP_400_BAD_REQUEST)
Instead of performing this validation manually, could you use a Django Rest Framework serializer to get consistent validation?

2023-06-02 18:04 UTC, raphaelm commented on doc/api/resources/orders.rst
> +   :statuscode 503: The email could not be sent.
```suggestion
   :statuscode 503: The email could not be sent.

```

2023-06-02 18:04 UTC, raphaelm commented on doc/api/resources/orders.rst
> +   :statuscode 200: no error
```suggestion
   :statuscode 204: Successful execution (email might not be sent yet, but queued to send)
```

2023-06-05 20:11 UTC, chschenk commented
Hi,
thanks for the review! I have updated this PR accordingly. Please let me know, if there is anything else which i can do to improve this PR.

2024-04-08 18:35 UTC, chschenk commented
Hi, is there anything i can do to move this PR forward?

2024-04-09 07:33 UTC, raphaelm commented
Sorry, this is on me. I never got around to prioritize work on making this abuse-safe for pretix Hosted. I'll look into it again when I have time, thanks for pushing it up the list!

2026-07-06 09:14 UTC, raphaelm commented
I think something like this will happen some day, not sure what yet, but closing this PR because we are drowning a little in PRs. It's still around if we need it.

2026-07-06 09:14 UTC, closed without merging