Check-in: Show more information
pretix/pretix pull request #3576
Opened 2023-09-06 10:29 UTC by raphaelm

This adds the necessary APIs to show additional information in the pretixSCAN apps during a checkin:

- A selection of questions through a new attribute ``show_during_checkin``
- A set of custom texts which can be configured on every level that we have `checkin_attention` on (item, variation, order) but that can also be used without `checkin_attention`

- [x] implementation
- [x] tests
- [x] support in web checkin
- [x] support in simulator
- [ ] libpretixsync support
  - [ ] pretixscan android release
  - [ ] pretixscan desktop release
  - [ ] pretixscan proxy release
- [ ] pretixscan-ios support

2023-09-27 08:22 UTC, robbi5 commented on src/pretix/base/exporters/json.py
> +                                'checkin_Text': variation.checkin_text,
```suggestion
                                'checkin_text': variation.checkin_text,
```

2023-09-28 10:55 UTC, robbi5 commented
Do we want to support the texts in the Search Result (`checkinrpc/search`) too? Then `CheckinListOrderPositionSerializer` needs `checkin_text`(`s`?), or? :)

2023-09-28 13:30 UTC, robbi5 commented
When doing a checkin in online mode, pretixSCAN would need the `question`s too from the `redeem`-endpoint. Currently `positions.answers` is available, but the (id-referenced) `question`s are only set on status `incomplete`.

2023-09-28 14:00 UTC, raphaelm commented
> Do we want to support the texts in the Search Result (`checkinrpc/search`) too? Then `CheckinListOrderPositionSerializer` needs `checkin_text`(`s`?), or? :)

Looking at the intended uses of the texts, I'd argue for "no". It would also make the search results quite long

2023-09-28 14:01 UTC, raphaelm commented
> When doing a checkin in online mode, pretixSCAN would need the `questions` too from the `redeem`-endpoint. Currently `position.answers` is available, but the (id-referenced) `questions` are only set on status `incomplete`.

Hmm, yes, we could change that, or rely on them being synced (which they always should be in our apps, right?)

2023-09-28 14:29 UTC, robbi5 commented
> > Do we want to support the texts in the Search Result (`checkinrpc/search`) too? Then `CheckinListOrderPositionSerializer` needs `checkin_text`(`s`?), or? :)
> 
> Looking at the intended uses of the texts, I'd argue for "no". It would also make the search results quite long

Ah, I misunderstood the usage of SearchResult in the pretixSCAN code, though that data is also used for the redeem result card. Thats not the case - so yeah, let's don't do that.

> > When doing a checkin in online mode, pretixSCAN would need the `questions` too from the `redeem`-endpoint. Currently `position.answers` is available, but the (id-referenced) `questions` are only set on status `incomplete`.
> 
> Hmm, yes, we could change that, or rely on them being synced (which they always should be in our apps, right?)

Well, as an api consumer (like that the web check in now also needs to pull data from two sources) I think it's cleaner that the api response delivers all the needed data that we want to show. The checkin list data, for example, is also returned in a (successful) checkin.

2023-09-28 14:29 UTC, robbi5 commented
> > Do we want to support the texts in the Search Result (`checkinrpc/search`) too? Then `CheckinListOrderPositionSerializer` needs `checkin_text`(`s`?), or? :)
> 
> Looking at the intended uses of the texts, I'd argue for "no". It would also make the search results quite long

Ah, I misunderstood the usage of SearchResult in the pretixSCAN code, though that data is also used for the redeem result card. Thats not the case - so yeah, let's don't do that.

> > When doing a checkin in online mode, pretixSCAN would need the `questions` too from the `redeem`-endpoint. Currently `position.answers` is available, but the (id-referenced) `questions` are only set on status `incomplete`.
> 
> Hmm, yes, we could change that, or rely on them being synced (which they always should be in our apps, right?)

Well, as an api consumer (like that the web check in now also needs to pull data from two sources) I think it's cleaner that the api response delivers all the needed data that we want to show. The checkin list data, for example, is also returned in a (successful) checkin.

2023-09-28 15:23 UTC, raphaelm commented
Ok, will look into it if it's possible in a good way

2023-09-28 16:06 UTC, robbi5 commented
locally I tried it temporarily by adding the following to the `return Response`-calls in `pretix/api/views/checkin.py`:
```py
'questions': [
   QuestionSerializer(q).data for q in op.item.questions.filter(show_during_checkin=True)
],
```

I still have to check what would be the best way to serve the questions when some have to still be answered on checkin but others already can be shown :)

2023-11-06 11:20 UTC, pc-coholic requested changes

2023-11-06 11:20 UTC, pc-coholic commented on src/pretix/control/templates/pretixcontrol/global_sysreport.html
This file does not seem to belong to this PR

2023-11-06 11:20 UTC, pc-coholic commented on doc/api/resources/item_variations.rst
> +.. versionchanged:: 2023.8
```suggestion
.. versionchanged:: 2023.10
```

2023-11-06 11:20 UTC, pc-coholic commented on doc/api/resources/items.rst
> +.. versionchanged:: 2023.8
```suggestion
.. versionchanged:: 2023.10
```

2023-11-06 11:20 UTC, pc-coholic commented on doc/api/resources/orders.rst
> +   The ``event`` and ``checkin_text`` attributes has been added. The organizer-level endpoint has been added.
This should probably a whole new `..versionchanged` that only includes the `checkin_text` (at 2023.10) and leave the `event` to the existing 2023.8.

2023-11-06 11:20 UTC, pc-coholic commented on doc/api/resources/questions.rst
> +.. versionchanged:: 2023.8
```suggestion
.. versionchanged:: 2023.10
```

2023-11-06 11:21 UTC, pc-coholic commented
Read through it only - but looks good to me from that POV

2023-11-28 13:52 UTC, merged