Widget: pass utm-params from embedding page to presale (Z#23146288)
pretix/pretix pull request #3962
Opened 2024-03-07 15:18 UTC by wiffbi

2024-03-11 12:08 UTC, raphaelm approved these changes

2024-03-11 12:10 UTC, raphaelm requested changes
Oh no, I noticed a problem right after approach. When the widget is set to open in a new tab (e.g. no SSL), the form where you select products opens in a new tab as a POST request that then gets redirected. So the utm parameters never get passed to a page where JS runs. Do we need to pull them through the redirect on the server side?

2024-03-11 12:27 UTC, wiffbi commented
Oh, yes, that is a good catch! I will look into this.

2024-03-19 11:20 UTC, raphaelm approved these changes

2024-03-20 08:19 UTC, merged