Stripe: Add support for Swish
pretix/pretix pull request #4149
Opened 2024-05-16 11:18 UTC by raphaelm

2024-05-16 11:21 UTC, pc-coholic requested changes

2024-05-16 11:21 UTC, pc-coholic commented on src/pretix/plugins/stripe/payment.py
> +        'This payment method is available to users of the Swedish apps Swish and BankID. Please keep your app '
```suggestion
        'This payment method is available to users of the Swedish apps Swish and BankID. Please have your app '
```

2024-05-17 10:03 UTC, luelista approved these changes
lokal getestet, funktioniert

2024-05-17 11:32 UTC, raphaelm commented on src/pretix/plugins/stripe/payment.py
> +                                 'before they work properly.'),
good point, aber dann mach doch gerne einen weiteren PR dafür auf, bevor wir das jetzt für nur die eine methode einführen :)

2024-05-17 11:33 UTC, merged