Cross-selling: Use different label if there are no add-on products
pretix/pretix pull request #4577
Opened 2024-10-28 11:14 UTC by raphaelm

Before:

![image](https://github.com/user-attachments/assets/7c70c6ed-78e5-473b-9e46-cb213dccfaf7)

After:

![Screenshot 2024-10-28 at 12-13-22 Step 1 of 5 Add-on products – Checkout Cross-selling test shop](https://github.com/user-attachments/assets/c5d77d29-dbfa-4328-a5fa-0010ca67300c)

2024-10-28 12:09 UTC, wiffbi requested changes
I guess it was accidental, that you remoced the form-element? Otherwise the addon-step does not work in my tests.

2024-10-28 12:09 UTC, wiffbi commented on src/pretix/presale/templates/pretixpresale/event/checkout_addons.html
> +    <div class="form-horizontal" method="post" data-asynctask
Why did you remove the form? It does not work without it in my tests.

```suggestion
    <form class="form-horizontal" method="post" data-asynctask
```

2024-10-28 12:11 UTC, raphaelm commented
argh, when the IDE tries to be clever but isn't...

2024-10-28 12:48 UTC, wiffbi requested changes
Looks good, but just stumbled upon a potential a11y problem regarding details/summary.

2024-10-28 12:48 UTC, wiffbi commented on src/pretix/presale/templates/pretixpresale/event/checkout_addons.html
> +                <div class="panel panel-default cross-selling">
Hm, just stumbled upon this. It creates invalid HTML in combination with the summary element. Not that it’s super bad, but not ideal for a11y. So could you move the whole summary-block with headline „more recomandations“ into the if-block and in the else-block replace the summary-tag with a div.

2024-10-29 08:47 UTC, wiffbi approved these changes

2024-10-29 08:53 UTC, merged